// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8Q6oneKz-mhbNwXtJuExI3TA5YJX470',
    appId: '1:338502364942:web:c7d7504505dbd4fad2715f',
    messagingSenderId: '338502364942',
    projectId: 'aitesting-b7e49',
    authDomain: 'aitesting-b7e49.firebaseapp.com',
    storageBucket: 'aitesting-b7e49.firebasestorage.app',
    measurementId: 'G-YT54YLDGTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgfLf48-Bf1JWIc3wfUaHicCBSjJQtRLQ',
    appId: '1:338502364942:android:e623e3180798448dd2715f',
    messagingSenderId: '338502364942',
    projectId: 'aitesting-b7e49',
    storageBucket: 'aitesting-b7e49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEjdzKoMO78PQGq7BWT0GiipcNjyMRekg',
    appId: '1:338502364942:ios:17a0e7455366c0ead2715f',
    messagingSenderId: '338502364942',
    projectId: 'aitesting-b7e49',
    storageBucket: 'aitesting-b7e49.firebasestorage.app',
    iosBundleId: 'com.example.aiTestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEjdzKoMO78PQGq7BWT0GiipcNjyMRekg',
    appId: '1:338502364942:ios:17a0e7455366c0ead2715f',
    messagingSenderId: '338502364942',
    projectId: 'aitesting-b7e49',
    storageBucket: 'aitesting-b7e49.firebasestorage.app',
    iosBundleId: 'com.example.aiTestProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr8Q6oneKz-mhbNwXtJuExI3TA5YJX470',
    appId: '1:338502364942:web:e400abff31c90063d2715f',
    messagingSenderId: '338502364942',
    projectId: 'aitesting-b7e49',
    authDomain: 'aitesting-b7e49.firebaseapp.com',
    storageBucket: 'aitesting-b7e49.firebasestorage.app',
    measurementId: 'G-RN8N6HRV32',
  );
}
